cvm-version: 0.14.10
cpus: 2
memory: 8192

cvm-network:
  inbound-ports: [22]

attested-keys:
  - id: host-ssh
    key: ecdsa-p256

networks:
  dev:
    egress: open

volumes:
  - name: workspace
    exec: true

containers:
  - name: "workspace"
    image: "ghcr.io/tinfoilsh/confidential-ubuntu-tinfoil-test@sha256:12cab483897c495f18a8a76c3ff8a102c0bbcb80c0677aa81253c8275e01ca1e" # v0.3.0
    restart: on-failure
    cvm_admin: true
    stop_signal: SIGRTMIN+3
    stop_timeout: 120
    networks: [dev]
    volumes: [workspace:/mnt/disk]
    keys: [host-ssh]

    ports: ["22:22"]

    env:
      - SSH_KEYS: |-
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDwPRs3ZguLD3xFvAdtQqjeRsUP9jCJ/6JXN9ruPJEhr cardno:22_545_924

    tmpfs:
      /run: "rw,nosuid,nodev,mode=755"

    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 30s

shim:
  upstream-port: 22
  authenticated: false
